services:
  app:
    build: .
    container_name: cloud-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
      - .env
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./app:/app/app
    restart: always

  db:
    image: mysql:8.0
    container_name: cloud-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
